# Item, location and option IDs: the single source of truth for both this world and the Starship client
# (tools/ap_gen_ids.py generates the client's C enums from this file). Edited by hand. Item and location
# groups are not listed here: they come from the "type" / "group" fields in data/.
#
# Never renumber or reuse an existing ID: seeds, slot saves and the client all refer to them. Add new
# entries with new numbers, and bump world_version in archipelago.json whenever IDs or slot_data change.

option_name_to_id = {
    "deathlink": 0,
    "ringlink": 1,
    "victory_condition": 2,
    "required_medals": 3,
    "level_access": 4,
    "shuffle_starting_level": 5,
    "shuffle_medals": 6,
    "shuffle_checkpoints": 7,
    "accomplished_sends_complete": 8,
    "radio_rando": 9,
    "engine_glow": 10,
    "default_lives": 11,
    "medal_corneria": 12,
    "medal_meteo": 13,
    "medal_sector_y": 14,
    "medal_katina": 15,
    "medal_fortuna": 16,
    "medal_aquas": 17,
    "medal_solar": 18,
    "medal_sector_x": 19,
    "medal_zoness": 20,
    "medal_titania": 21,
    "medal_sector_z": 22,
    "medal_macbeth": 23,
    "medal_area_6": 24,
    "medal_bolse": 25,
    "medal_venom": 26,
}

item_name_to_id = {
    "None": -1,
    "Nothing": 1,
    "Laser Upgrade": 2,
    "Silver Ring": 3,
    "Silver Star": 4,
    "Gold Ring": 5,
    "Bomb": 6,
    "Extra Arwing": 7,
    "Medal": 8,
    "Corneria - Checkpoint": 9,
    "Meteo - Checkpoint": 10,
    "Sector X - Checkpoint": 11,
    "Titania - Checkpoint": 12,
    "Sector Y - Checkpoint": 13,
    "Aquas - Checkpoint": 14,
    "Zoness - Checkpoint": 15,
    "Area 6 - Checkpoint": 16,
    "Solar - Checkpoint": 17,
    "Macbeth - Checkpoint": 18,
    "Venom 1 - Checkpoint": 19,
    "Corneria": 20,
    "Meteo": 21,
    "Sector X": 22,
    "Area 6": 23,
    "Sector Y": 24,
    "Venom": 25,
    "Solar": 26,
    "Zoness": 27,
    "Macbeth": 28,
    "Titania": 29,
    "Aquas": 30,
    "Fortuna": 31,
    "Katina": 32,
    "Bolse": 33,
    "Sector Z": 34,
    "Aquas - Red Path": 35,
    "Area 6 - Red Path": 36,
    "Bolse - Blue Path": 37,
    "Corneria - Blue Path": 38,
    "Corneria - Red Path": 39,
    "Fortuna - Blue Path": 40,
    "Fortuna - Yellow Path": 41,
    "Katina - Blue Path": 42,
    "Katina - Yellow Path": 43,
    "Macbeth - Blue Path": 44,
    "Macbeth - Red Path": 45,
    "Meteo - Blue Path": 46,
    "Meteo - Warp Path": 47,
    "Sector X - Blue Path": 48,
    "Sector X - Yellow Path": 49,
    "Sector X - Warp Path": 50,
    "Sector Y - Yellow Path": 51,
    "Sector Y - Red Path": 52,
    "Sector Z - Blue Path": 53,
    "Sector Z - Red Path": 54,
    "Solar - Yellow Path": 55,
    "Titania - Blue Path": 56,
    "Zoness - Yellow Path": 57,
    "Zoness - Red Path": 58,
    "Defeated Robot Andross": 59,
    "Defeated Andross": 60,
}

location_name_to_id = {
    "None": -1,
    "Goal Completed": 0,
    "Starting Level": 1,
    "Aquas - Mission Complete": 2,
    "Aquas - Medal": 3,
    "Aquas - Checkpoint": 4,
    "Area 6 - Mission Complete": 5,
    "Area 6 - Medal": 6,
    "Area 6 - Below Early Defense Station: Gold Ring": 7,
    "Area 6 - Above Early Defense Station: Laser Upgrade": 8,
    "Area 6 - Andross' Taunt: Gold Ring": 9,
    "Area 6 - Checkpoint": 10,
    "Area 6 - Near Defense Station After Checkpoint: Gold Ring": 11,
    "Bolse - Mission Complete": 12,
    "Bolse - Medal": 13,
    "Corneria - Mission Complete": 14,
    "Corneria - Mission Accomplished": 15,
    "Corneria - Medal": 16,
    "Corneria - Under Arch: Gold Ring": 17,
    "Corneria - Behind Doors: Bomb": 18,
    "Corneria - Center Of Corneria City: Silver Ring": 19,
    "Corneria - Near First Ground Robot: Laser Upgrade": 20,
    "Corneria - Under Highway Arch: Gold Ring": 21,
    "Corneria - Behind Second Ground Robot: Bomb": 22,
    "Corneria - Behind Doors Near Checkpoint: Gold Ring": 23,
    "Corneria - Checkpoint": 24,
    "Corneria - After Falco's G-Diffuser Issue: Laser Upgrade": 25,
    "Corneria - After Falco's G-Diffuser Issue: Bomb": 26,
    "Corneria - Water Section Last Arch: Gold Ring": 27,
    "Corneria - Left Of Waterfall: Laser Upgrade": 28,
    "Corneria - Before Mission Complete Boss, Lower: Gold Ring": 29,
    "Corneria - Before Mission Complete Boss, Upper: Gold Ring": 30,
    "Fortuna - Mission Complete": 31,
    "Fortuna - Mission Accomplished": 32,
    "Fortuna - Medal": 33,
    "Katina - Mission Complete": 34,
    "Katina - Mission Accomplished": 35,
    "Katina - Medal": 36,
    "Macbeth - Mission Complete": 37,
    "Macbeth - Mission Accomplished": 38,
    "Macbeth - Medal": 39,
    "Macbeth - Before Hill With Rolling Rocks: Bomb": 40,
    "Macbeth - Above Rolling Rocks: Gold Ring": 41,
    "Macbeth - On Tracks Before Bridge: Gold Ring": 42,
    "Macbeth - On Tracks After Bridge: Gold Ring": 43,
    "Macbeth - Checkpoint": 44,
    "Macbeth - After First Building: Silver Ring": 45,
    "Macbeth - Before Buildings Three And Four: Silver Ring": 46,
    "Macbeth - After Buildings Three And Four, Right: Silver Ring": 47,
    "Macbeth - Before Building Five: Silver Ring": 48,
    "Macbeth - After Building Five: Gold Ring": 49,
    "Macbeth - Under Bridge After Checkpoint: Bomb": 50,
    "Macbeth - First Building After Switcher: Gold Ring": 51,
    "Macbeth - Second Building After Switcher: Silver Ring": 52,
    "Macbeth - After Marker 100: Silver Ring": 53,
    "Macbeth - Before Marker 300: Silver Ring": 54,
    "Meteo - Mission Complete": 55,
    "Meteo - Warp": 56,
    "Meteo - Medal": 57,
    "Meteo - After Starting Asteroids: Gold Ring": 58,
    "Meteo - End Of First Tunnel, Top: Silver Ring": 59,
    "Meteo - End Of First Tunnel, Middle: Gold Ring": 60,
    "Meteo - End Of First Tunnel, Bottom: Bomb": 61,
    "Meteo - Between Two Big Asteroids: Bomb": 62,
    "Meteo - Checkpoint": 63,
    "Meteo - Near Warp Rings: Gold Ring": 64,
    "Meteo - Just Before Boss: Gold Ring": 65,
    "Sector X - Mission Complete": 66,
    "Sector X - Mission Accomplished": 67,
    "Sector X - Warp": 68,
    "Sector X - Medal": 69,
    "Sector X - In Debris Field, Left: Gold Ring": 70,
    "Sector X - Checkpoint": 71,
    "Sector X - Behind Enemy After Peppy Gets Chased, Right: Gold Ring": 72,
    "Sector X - Left Path - Just After Fork, Through Bottom Slot: Laser Upgrade": 73,
    "Sector X - Left Path - Closing Door Section: Gold Ring": 74,
    "Sector X - Left Path - After Closing Door Section: Bomb": 75,
    "Sector X - Left Path - Behind First Warp Gate: Gold Ring": 76,
    "Sector X - Left Path - After First Warp Gate, Up High: Bomb": 77,
    "Sector X - Left Path - Before Final Warp Gate: Gold Ring": 78,
    "Sector Y - Mission Complete": 79,
    "Sector Y - Mission Accomplished": 80,
    "Sector Y - Medal": 81,
    "Sector Y - Above Friendly Ship Near Start: Gold Ring": 82,
    "Sector Y - Before Checkpoint: Gold Ring": 83,
    "Sector Y - Checkpoint": 84,
    "Sector Y - Breaking Through The Enemy Fleet, Beginning: Gold Ring": 85,
    "Sector Y - Breaking Through The Enemy Fleet, Middle: Gold Ring": 86,
    "Sector Y - Breaking Through The Enemy Fleet, End: Gold Ring": 87,
    "Sector Z - Mission Complete": 88,
    "Sector Z - Mission Accomplished": 89,
    "Sector Z - Medal": 90,
    "Solar - Mission Complete": 91,
    "Solar - Medal": 92,
    "Solar - Checkpoint": 93,
    "Titania - Mission Complete": 94,
    "Titania - Medal": 95,
    "Titania - Second Falling Tower From Start: Bomb": 96,
    "Titania - Through Two Leaning Towers: Gold Ring": 97,
    "Titania - After Three Bone Structures: Bomb": 98,
    "Titania - Above Skull: Silver Ring": 99,
    "Titania - On Bridge: Gold Ring": 100,
    "Titania - Right Of Bridge: Gold Ring": 101,
    "Titania - Upper Left Path: Bomb": 102,
    "Titania - Suspended Above Two Bridges: Silver Ring": 103,
    "Titania - Checkpoint": 104,
    "Titania - Falling Towers Section: First Bomb": 105,
    "Titania - Falling Towers Section: Gold Ring": 106,
    "Titania - Falling Towers Section: Second Bomb": 107,
    "Titania - Falling Towers Section: Third Bomb": 108,
    "Titania - Behind Arches On The Right: Gold Ring": 109,
    "Titania - Upper Right Hill: Gold Ring": 110,
    "Titania - First Falling Tower Before Boss: Silver Ring": 111,
    "Titania - First Falling Tower Before Boss: Gold Ring": 112,
    "Titania - Second Falling Tower Before Boss: Silver Ring": 113,
    "Titania - Second Falling Tower Before Boss: Gold Ring": 114,
    "Venom - Medal": 115,
    "Venom - Defeat Robot Andross": 116,
    "Venom 1 - Near Start, Bottom: Gold Ring": 117,
    "Venom 1 - Near Start, Top: Laser Upgrade": 118,
    "Venom 1 - Maze (R R R): Gold Ring": 119,
    "Venom 1 - Maze (L L): Gold Ring": 120,
    "Venom 1 - Maze (R R L L): Gold Ring": 121,
    "Venom 1 - End Of Maze (R R R R): Gold Ring": 122,
    "Venom 1 - End Of Maze (L L L): Gold Ring": 123,
    "Venom 1 - End Of Maze (R R L L): Gold Ring": 124,
    "Venom 1 - Checkpoint": 125,
    "Venom - Defeat Andross": 126,
    "Zoness - Mission Complete": 127,
    "Zoness - Mission Accomplished": 128,
    "Zoness - Medal": 129,
    "Zoness - Before Katt Appears, Top: Gold Ring": 130,
    "Zoness - Before Katt Appears, Middle: Silver Ring": 131,
    "Zoness - Before Katt Appears, Bottom: Bomb": 132,
    "Zoness - Checkpoint": 133,
    "Zoness - Aim For The Rudder, First Gate: Laser Upgrade": 134,
    "Zoness - Aim For The Rudder, Second Gate, Left: Bomb": 135,
    "Zoness - Aim For The Rudder, Third Gate: Silver Ring": 136,
}
