// Automatically generated by tools/ap_gen_ids.py from the apworld data. DO NOT EDIT.
// Source: apworld/star_fox_64_ss/data (logic strings) and options.py

#include "ApGame.h"
#include "ApLogic.h"

// Received count of an item as the logic sees it (medals may be earned locally when unshuffled).
static int ApLogic_Count(int item) {
    if (item == AP_ITEM_MEDAL) {
        return ApMission_MedalCount();
    }
    return AP_GetItemCount((uint16_t) item);
}

typedef bool (*ApRuleFn)(void);

// Menu -> Corneria
static bool Rule0(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) || ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_CORNERIA) >= 1)));
}

// Menu -> Meteo
static bool Rule1(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_METEO) >= 1));
}

// Menu -> Sector X
static bool Rule2(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_SECTOR_X) >= 1));
}

// Menu -> Area 6
static bool Rule3(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_AREA_6) >= 1));
}

// Menu -> Sector Y
static bool Rule4(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_SECTOR_Y) >= 1));
}

// Menu -> Venom 1
static bool Rule5(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_VENOM) >= 1) && ((AP_GetOption(AP_OPTION_VICTORY_CONDITION) != AP_OPTION_VICTORY_CONDITION_ANDROSS_OR_ROBOT_ANDROSS) || (ApLogic_Count(AP_ITEM_MEDAL) >= AP_GetOption(AP_OPTION_REQUIRED_MEDALS))));
}

// Menu -> Venom 2
static bool Rule6(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_VENOM) >= 1) && (ApLogic_Count(AP_ITEM_MEDAL) >= AP_GetOption(AP_OPTION_REQUIRED_MEDALS)));
}

// Menu -> Solar
static bool Rule7(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_SOLAR) >= 1));
}

// Menu -> Zoness
static bool Rule8(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_ZONESS) >= 1));
}

// Menu -> Macbeth
static bool Rule9(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_MACBETH) >= 1));
}

// Menu -> Titania
static bool Rule10(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_TITANIA) >= 1));
}

// Menu -> Aquas
static bool Rule11(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_AQUAS) >= 1));
}

// Menu -> Fortuna
static bool Rule12(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_FORTUNA) >= 1));
}

// Menu -> Katina
static bool Rule13(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_KATINA) >= 1));
}

// Menu -> Bolse
static bool Rule14(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_BOLSE) >= 1));
}

// Menu -> Sector Z
static bool Rule15(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS) && (ApLogic_Count(AP_ITEM_SECTOR_Z) >= 1));
}

// Aquas -> Zoness
static bool Rule16(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_AQUAS_RED_PATH) >= 1));
}

// Area 6 -> Venom 2
static bool Rule17(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_AREA_6_RED_PATH) >= 1) && (ApLogic_Count(AP_ITEM_MEDAL) >= AP_GetOption(AP_OPTION_REQUIRED_MEDALS)));
}

// Bolse -> Venom 1
static bool Rule18(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_BOLSE_BLUE_PATH) >= 1) && ((AP_GetOption(AP_OPTION_VICTORY_CONDITION) != AP_OPTION_VICTORY_CONDITION_ANDROSS_OR_ROBOT_ANDROSS) || (ApLogic_Count(AP_ITEM_MEDAL) >= AP_GetOption(AP_OPTION_REQUIRED_MEDALS))));
}

// Corneria -> Meteo
static bool Rule19(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_CORNERIA_BLUE_PATH) >= 1));
}

// Corneria -> Sector Y
static bool Rule20(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_CORNERIA_RED_PATH) >= 1));
}

// Fortuna -> Sector X
static bool Rule21(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_FORTUNA_BLUE_PATH) >= 1));
}

// Fortuna -> Solar
static bool Rule22(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_FORTUNA_YELLOW_PATH) >= 1));
}

// Katina -> Sector X
static bool Rule23(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_KATINA_BLUE_PATH) >= 1));
}

// Katina -> Solar
static bool Rule24(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_KATINA_YELLOW_PATH) >= 1));
}

// Macbeth -> Bolse
static bool Rule25(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_MACBETH_BLUE_PATH) >= 1));
}

// Macbeth -> Area 6
static bool Rule26(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_MACBETH_RED_PATH) >= 1));
}

// Meteo -> Fortuna
static bool Rule27(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_METEO_BLUE_PATH) >= 1));
}

// Meteo -> Katina
static bool Rule28(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_METEO_WARP_PATH) >= 1));
}

// Sector X -> Titania
static bool Rule29(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_SECTOR_X_BLUE_PATH) >= 1));
}

// Sector X -> Macbeth
static bool Rule30(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_SECTOR_X_YELLOW_PATH) >= 1));
}

// Sector X -> Sector Z
static bool Rule31(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_SECTOR_X_WARP_PATH) >= 1));
}

// Sector Y -> Katina
static bool Rule32(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_SECTOR_Y_YELLOW_PATH) >= 1));
}

// Sector Y -> Aquas
static bool Rule33(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_SECTOR_Y_RED_PATH) >= 1));
}

// Sector Z -> Bolse
static bool Rule34(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_SECTOR_Z_BLUE_PATH) >= 1));
}

// Sector Z -> Area 6
static bool Rule35(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_SECTOR_Z_RED_PATH) >= 1));
}

// Solar -> Macbeth
static bool Rule36(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_SOLAR_YELLOW_PATH) >= 1));
}

// Titania -> Bolse
static bool Rule37(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_TITANIA_BLUE_PATH) >= 1));
}

// Zoness -> Macbeth
static bool Rule38(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_ZONESS_YELLOW_PATH) >= 1));
}

// Zoness -> Sector Z
static bool Rule39(void) {
    return ((AP_GetOption(AP_OPTION_LEVEL_ACCESS) == AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS) && (ApLogic_Count(AP_ITEM_ZONESS_RED_PATH) >= 1));
}

const char* const gApRegionNames[AP_REGION_MAX] = {
    "Menu",
    "Aquas",
    "Area 6",
    "Bolse",
    "Corneria",
    "Fortuna",
    "Katina",
    "Macbeth",
    "Meteo",
    "Sector X",
    "Sector Y",
    "Sector Z",
    "Solar",
    "Titania",
    "Venom",
    "Venom 1",
    "Venom 2",
    "Zoness",
};

const int8_t gApRegionPlanet[AP_REGION_MAX] = {
    -1, // Menu
    PLANET_AQUAS, // Aquas
    PLANET_AREA_6, // Area 6
    PLANET_BOLSE, // Bolse
    PLANET_CORNERIA, // Corneria
    PLANET_FORTUNA, // Fortuna
    PLANET_KATINA, // Katina
    PLANET_MACBETH, // Macbeth
    PLANET_METEO, // Meteo
    PLANET_SECTOR_X, // Sector X
    PLANET_SECTOR_Y, // Sector Y
    PLANET_SECTOR_Z, // Sector Z
    PLANET_SOLAR, // Solar
    PLANET_TITANIA, // Titania
    PLANET_VENOM, // Venom
    PLANET_VENOM, // Venom 1
    PLANET_VENOM, // Venom 2
    PLANET_ZONESS, // Zoness
};

typedef struct {
    uint8_t from;
    uint8_t to;
    ApRuleFn rule; // NULL = always
} ApExit;

static const ApExit sExits[42] = {
    { AP_REGION_MENU, AP_REGION_CORNERIA, Rule0 },
    { AP_REGION_MENU, AP_REGION_METEO, Rule1 },
    { AP_REGION_MENU, AP_REGION_SECTOR_X, Rule2 },
    { AP_REGION_MENU, AP_REGION_AREA_6, Rule3 },
    { AP_REGION_MENU, AP_REGION_SECTOR_Y, Rule4 },
    { AP_REGION_MENU, AP_REGION_VENOM_1, Rule5 },
    { AP_REGION_MENU, AP_REGION_VENOM_2, Rule6 },
    { AP_REGION_MENU, AP_REGION_SOLAR, Rule7 },
    { AP_REGION_MENU, AP_REGION_ZONESS, Rule8 },
    { AP_REGION_MENU, AP_REGION_MACBETH, Rule9 },
    { AP_REGION_MENU, AP_REGION_TITANIA, Rule10 },
    { AP_REGION_MENU, AP_REGION_AQUAS, Rule11 },
    { AP_REGION_MENU, AP_REGION_FORTUNA, Rule12 },
    { AP_REGION_MENU, AP_REGION_KATINA, Rule13 },
    { AP_REGION_MENU, AP_REGION_BOLSE, Rule14 },
    { AP_REGION_MENU, AP_REGION_SECTOR_Z, Rule15 },
    { AP_REGION_AQUAS, AP_REGION_ZONESS, Rule16 },
    { AP_REGION_AREA_6, AP_REGION_VENOM_2, Rule17 },
    { AP_REGION_BOLSE, AP_REGION_VENOM_1, Rule18 },
    { AP_REGION_CORNERIA, AP_REGION_METEO, Rule19 },
    { AP_REGION_CORNERIA, AP_REGION_SECTOR_Y, Rule20 },
    { AP_REGION_FORTUNA, AP_REGION_SECTOR_X, Rule21 },
    { AP_REGION_FORTUNA, AP_REGION_SOLAR, Rule22 },
    { AP_REGION_KATINA, AP_REGION_SECTOR_X, Rule23 },
    { AP_REGION_KATINA, AP_REGION_SOLAR, Rule24 },
    { AP_REGION_MACBETH, AP_REGION_BOLSE, Rule25 },
    { AP_REGION_MACBETH, AP_REGION_AREA_6, Rule26 },
    { AP_REGION_METEO, AP_REGION_FORTUNA, Rule27 },
    { AP_REGION_METEO, AP_REGION_KATINA, Rule28 },
    { AP_REGION_SECTOR_X, AP_REGION_TITANIA, Rule29 },
    { AP_REGION_SECTOR_X, AP_REGION_MACBETH, Rule30 },
    { AP_REGION_SECTOR_X, AP_REGION_SECTOR_Z, Rule31 },
    { AP_REGION_SECTOR_Y, AP_REGION_KATINA, Rule32 },
    { AP_REGION_SECTOR_Y, AP_REGION_AQUAS, Rule33 },
    { AP_REGION_SECTOR_Z, AP_REGION_BOLSE, Rule34 },
    { AP_REGION_SECTOR_Z, AP_REGION_AREA_6, Rule35 },
    { AP_REGION_SOLAR, AP_REGION_MACBETH, Rule36 },
    { AP_REGION_TITANIA, AP_REGION_BOLSE, Rule37 },
    { AP_REGION_VENOM_1, AP_REGION_VENOM, NULL },
    { AP_REGION_VENOM_2, AP_REGION_VENOM, NULL },
    { AP_REGION_ZONESS, AP_REGION_MACBETH, Rule38 },
    { AP_REGION_ZONESS, AP_REGION_SECTOR_Z, Rule39 },
};

typedef struct {
    int8_t region; // -1 = not a location
    ApRuleFn rule;
} ApLocationRule;

static const ApLocationRule sLocations[AP_LOCATION_MAX] = {
    { -1, NULL }, // Goal Completed
    { -1, NULL }, // Starting Level
    { AP_REGION_AQUAS, NULL }, // Aquas - Mission Complete
    { AP_REGION_AQUAS, NULL }, // Aquas - Medal
    { AP_REGION_AQUAS, NULL }, // Aquas - Checkpoint
    { AP_REGION_AREA_6, NULL }, // Area 6 - Mission Complete
    { AP_REGION_AREA_6, NULL }, // Area 6 - Medal
    { AP_REGION_AREA_6, NULL }, // Area 6 - Below Early Defense Station: Gold Ring
    { AP_REGION_AREA_6, NULL }, // Area 6 - Above Early Defense Station: Laser Upgrade
    { AP_REGION_AREA_6, NULL }, // Area 6 - Andross' Taunt: Gold Ring
    { AP_REGION_AREA_6, NULL }, // Area 6 - Checkpoint
    { AP_REGION_AREA_6, NULL }, // Area 6 - Near Defense Station After Checkpoint: Gold Ring
    { AP_REGION_BOLSE, NULL }, // Bolse - Mission Complete
    { AP_REGION_BOLSE, NULL }, // Bolse - Medal
    { AP_REGION_CORNERIA, NULL }, // Corneria - Mission Complete
    { AP_REGION_CORNERIA, NULL }, // Corneria - Mission Accomplished
    { AP_REGION_CORNERIA, NULL }, // Corneria - Medal
    { AP_REGION_CORNERIA, NULL }, // Corneria - Under Arch: Gold Ring
    { AP_REGION_CORNERIA, NULL }, // Corneria - Behind Doors: Bomb
    { AP_REGION_CORNERIA, NULL }, // Corneria - Center Of Corneria City: Silver Ring
    { AP_REGION_CORNERIA, NULL }, // Corneria - Near First Ground Robot: Laser Upgrade
    { AP_REGION_CORNERIA, NULL }, // Corneria - Under Highway Arch: Gold Ring
    { AP_REGION_CORNERIA, NULL }, // Corneria - Behind Second Ground Robot: Bomb
    { AP_REGION_CORNERIA, NULL }, // Corneria - Behind Doors Near Checkpoint: Gold Ring
    { AP_REGION_CORNERIA, NULL }, // Corneria - Checkpoint
    { AP_REGION_CORNERIA, NULL }, // Corneria - After Falco's G-Diffuser Issue: Laser Upgrade
    { AP_REGION_CORNERIA, NULL }, // Corneria - After Falco's G-Diffuser Issue: Bomb
    { AP_REGION_CORNERIA, NULL }, // Corneria - Water Section Last Arch: Gold Ring
    { AP_REGION_CORNERIA, NULL }, // Corneria - Left Of Waterfall: Laser Upgrade
    { AP_REGION_CORNERIA, NULL }, // Corneria - Before Mission Complete Boss, Lower: Gold Ring
    { AP_REGION_CORNERIA, NULL }, // Corneria - Before Mission Complete Boss, Upper: Gold Ring
    { AP_REGION_FORTUNA, NULL }, // Fortuna - Mission Complete
    { AP_REGION_FORTUNA, NULL }, // Fortuna - Mission Accomplished
    { AP_REGION_FORTUNA, NULL }, // Fortuna - Medal
    { AP_REGION_KATINA, NULL }, // Katina - Mission Complete
    { AP_REGION_KATINA, NULL }, // Katina - Mission Accomplished
    { AP_REGION_KATINA, NULL }, // Katina - Medal
    { AP_REGION_MACBETH, NULL }, // Macbeth - Mission Complete
    { AP_REGION_MACBETH, NULL }, // Macbeth - Mission Accomplished
    { AP_REGION_MACBETH, NULL }, // Macbeth - Medal
    { AP_REGION_MACBETH, NULL }, // Macbeth - Before Hill With Rolling Rocks: Bomb
    { AP_REGION_MACBETH, NULL }, // Macbeth - Above Rolling Rocks: Gold Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - On Tracks Before Bridge: Gold Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - On Tracks After Bridge: Gold Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - Checkpoint
    { AP_REGION_MACBETH, NULL }, // Macbeth - After First Building: Silver Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - Before Buildings Three And Four: Silver Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - After Buildings Three And Four, Right: Silver Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - Before Building Five: Silver Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - After Building Five: Gold Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - Under Bridge After Checkpoint: Bomb
    { AP_REGION_MACBETH, NULL }, // Macbeth - First Building After Switcher: Gold Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - Second Building After Switcher: Silver Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - After Marker 100: Silver Ring
    { AP_REGION_MACBETH, NULL }, // Macbeth - Before Marker 300: Silver Ring
    { AP_REGION_METEO, NULL }, // Meteo - Mission Complete
    { AP_REGION_METEO, NULL }, // Meteo - Warp
    { AP_REGION_METEO, NULL }, // Meteo - Medal
    { AP_REGION_METEO, NULL }, // Meteo - After Starting Asteroids: Gold Ring
    { AP_REGION_METEO, NULL }, // Meteo - End Of First Tunnel, Top: Silver Ring
    { AP_REGION_METEO, NULL }, // Meteo - End Of First Tunnel, Middle: Gold Ring
    { AP_REGION_METEO, NULL }, // Meteo - End Of First Tunnel, Bottom: Bomb
    { AP_REGION_METEO, NULL }, // Meteo - Between Two Big Asteroids: Bomb
    { AP_REGION_METEO, NULL }, // Meteo - Checkpoint
    { AP_REGION_METEO, NULL }, // Meteo - Near Warp Rings: Gold Ring
    { AP_REGION_METEO, NULL }, // Meteo - Just Before Boss: Gold Ring
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Mission Complete
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Mission Accomplished
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Warp
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Medal
    { AP_REGION_SECTOR_X, NULL }, // Sector X - In Debris Field, Left: Gold Ring
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Checkpoint
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Behind Enemy After Peppy Gets Chased, Right: Gold Ring
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Left Path - Just After Fork, Through Bottom Slot: Laser Upgrade
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Left Path - Closing Door Section: Gold Ring
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Left Path - After Closing Door Section: Bomb
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Left Path - Behind First Warp Gate: Gold Ring
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Left Path - After First Warp Gate, Up High: Bomb
    { AP_REGION_SECTOR_X, NULL }, // Sector X - Left Path - Before Final Warp Gate: Gold Ring
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Mission Complete
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Mission Accomplished
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Medal
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Above Friendly Ship Near Start: Gold Ring
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Before Checkpoint: Gold Ring
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Checkpoint
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Breaking Through The Enemy Fleet, Beginning: Gold Ring
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Breaking Through The Enemy Fleet, Middle: Gold Ring
    { AP_REGION_SECTOR_Y, NULL }, // Sector Y - Breaking Through The Enemy Fleet, End: Gold Ring
    { AP_REGION_SECTOR_Z, NULL }, // Sector Z - Mission Complete
    { AP_REGION_SECTOR_Z, NULL }, // Sector Z - Mission Accomplished
    { AP_REGION_SECTOR_Z, NULL }, // Sector Z - Medal
    { AP_REGION_SOLAR, NULL }, // Solar - Mission Complete
    { AP_REGION_SOLAR, NULL }, // Solar - Medal
    { AP_REGION_SOLAR, NULL }, // Solar - Checkpoint
    { AP_REGION_TITANIA, NULL }, // Titania - Mission Complete
    { AP_REGION_TITANIA, NULL }, // Titania - Medal
    { AP_REGION_TITANIA, NULL }, // Titania - Second Falling Tower From Start: Bomb
    { AP_REGION_TITANIA, NULL }, // Titania - Through Two Leaning Towers: Gold Ring
    { AP_REGION_TITANIA, NULL }, // Titania - After Three Bone Structures: Bomb
    { AP_REGION_TITANIA, NULL }, // Titania - Above Skull: Silver Ring
    { AP_REGION_TITANIA, NULL }, // Titania - On Bridge: Gold Ring
    { AP_REGION_TITANIA, NULL }, // Titania - Right Of Bridge: Gold Ring
    { AP_REGION_TITANIA, NULL }, // Titania - Upper Left Path: Bomb
    { AP_REGION_TITANIA, NULL }, // Titania - Suspended Above Two Bridges: Silver Ring
    { AP_REGION_TITANIA, NULL }, // Titania - Checkpoint
    { AP_REGION_TITANIA, NULL }, // Titania - Falling Towers Section: First Bomb
    { AP_REGION_TITANIA, NULL }, // Titania - Falling Towers Section: Gold Ring
    { AP_REGION_TITANIA, NULL }, // Titania - Falling Towers Section: Second Bomb
    { AP_REGION_TITANIA, NULL }, // Titania - Falling Towers Section: Third Bomb
    { AP_REGION_TITANIA, NULL }, // Titania - Behind Arches On The Right: Gold Ring
    { AP_REGION_TITANIA, NULL }, // Titania - Upper Right Hill: Gold Ring
    { AP_REGION_TITANIA, NULL }, // Titania - First Falling Tower Before Boss: Silver Ring
    { AP_REGION_TITANIA, NULL }, // Titania - First Falling Tower Before Boss: Gold Ring
    { AP_REGION_TITANIA, NULL }, // Titania - Second Falling Tower Before Boss: Silver Ring
    { AP_REGION_TITANIA, NULL }, // Titania - Second Falling Tower Before Boss: Gold Ring
    { AP_REGION_VENOM, NULL }, // Venom - Medal
    { AP_REGION_VENOM_1, NULL }, // Venom - Defeat Robot Andross
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - Near Start, Bottom: Gold Ring
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - Near Start, Top: Laser Upgrade
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - Maze (R R R): Gold Ring
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - Maze (L L): Gold Ring
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - Maze (R R L L): Gold Ring
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - End Of Maze (R R R R): Gold Ring
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - End Of Maze (L L L): Gold Ring
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - End Of Maze (R R L L): Gold Ring
    { AP_REGION_VENOM_1, NULL }, // Venom 1 - Checkpoint
    { AP_REGION_VENOM_2, NULL }, // Venom - Defeat Andross
    { AP_REGION_ZONESS, NULL }, // Zoness - Mission Complete
    { AP_REGION_ZONESS, NULL }, // Zoness - Mission Accomplished
    { AP_REGION_ZONESS, NULL }, // Zoness - Medal
    { AP_REGION_ZONESS, NULL }, // Zoness - Before Katt Appears, Top: Gold Ring
    { AP_REGION_ZONESS, NULL }, // Zoness - Before Katt Appears, Middle: Silver Ring
    { AP_REGION_ZONESS, NULL }, // Zoness - Before Katt Appears, Bottom: Bomb
    { AP_REGION_ZONESS, NULL }, // Zoness - Checkpoint
    { AP_REGION_ZONESS, NULL }, // Zoness - Aim For The Rudder, First Gate: Laser Upgrade
    { AP_REGION_ZONESS, NULL }, // Zoness - Aim For The Rudder, Second Gate, Left: Bomb
    { AP_REGION_ZONESS, NULL }, // Zoness - Aim For The Rudder, Third Gate: Silver Ring
};

static bool sReachable[AP_REGION_MAX];

void ApLogic_Update(void) {
    bool changed = true;
    int i;

    for (i = 0; i < AP_REGION_MAX; i++) {
        sReachable[i] = false;
    }
    sReachable[AP_REGION_MENU] = true;
    while (changed) {
        changed = false;
        for (i = 0; i < ARRAY_COUNT(sExits); i++) {
            if (!sReachable[sExits[i].from] || sReachable[sExits[i].to]) {
                continue;
            }
            if ((sExits[i].rule == NULL) || sExits[i].rule()) {
                sReachable[sExits[i].to] = true;
                changed = true;
            }
        }
    }
}

bool ApLogic_RegionReachable(int region) {
    return (region >= 0) && (region < AP_REGION_MAX) && sReachable[region];
}

int ApLogic_LocationRegion(uint16_t location) {
    return (location < AP_LOCATION_MAX) ? sLocations[location].region : -1;
}

bool ApLogic_LocationRule(uint16_t location) {
    if ((location >= AP_LOCATION_MAX) || (sLocations[location].region < 0)) {
        return false;
    }
    return (sLocations[location].rule == NULL) || sLocations[location].rule();
}

bool ApLogic_LocationInLogic(uint16_t location) {
    return ApLogic_LocationRule(location) && ApLogic_RegionReachable(ApLogic_LocationRegion(location));
}
