#pragma once

// Automatically generated by tools/ap_gen_ids.py from the apworld data. DO NOT EDIT.
// Region graph and access rules compiled from the world's logic strings, for the in-game tracker.

#include <stdint.h>
#include <stdbool.h>
#include "port/archipelago/ArchipelagoIds.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    AP_REGION_MENU,
    AP_REGION_AQUAS,
    AP_REGION_AREA_6,
    AP_REGION_BOLSE,
    AP_REGION_CORNERIA,
    AP_REGION_FORTUNA,
    AP_REGION_KATINA,
    AP_REGION_MACBETH,
    AP_REGION_METEO,
    AP_REGION_SECTOR_X,
    AP_REGION_SECTOR_Y,
    AP_REGION_SECTOR_Z,
    AP_REGION_SOLAR,
    AP_REGION_TITANIA,
    AP_REGION_VENOM,
    AP_REGION_VENOM_1,
    AP_REGION_VENOM_2,
    AP_REGION_ZONESS,
    AP_REGION_MAX,
} ApRegion;

extern const char* const gApRegionNames[AP_REGION_MAX];
extern const int8_t gApRegionPlanet[AP_REGION_MAX]; // PlanetId, -1 for non-level regions

void ApLogic_Update(void);                    // recompute region reachability from the current state
bool ApLogic_RegionReachable(int region);
int ApLogic_LocationRegion(uint16_t location); // -1 if the id is not a location
bool ApLogic_LocationRule(uint16_t location);  // the location's own rule, ignoring reachability
bool ApLogic_LocationInLogic(uint16_t location); // reachable region && rule

#ifdef __cplusplus
}
#endif
