#!/usr/bin/env python3
"""Generate src/port/archipelago/ArchipelagoIds.h and src/port/archipelago/game/ApTables.c from the apworld.

Usage: tools/ap_gen_ids.py [--apworld PATH] [--check]

Reads ids.py and version.py from the vendored world (apworld/star_fox_64_ss by default,
or an AP-Star-Fox-64 checkout) (plain dicts, no
Archipelago install needed) and emits C enums + name tables. Enum names use the
same name_to_c() rule as the ROM hack's tools/enum_gen.py so that game code can
be ported verbatim from n64/src/.
"""
import argparse
import importlib.util
import os
import re
import sys

sys.dont_write_bytecode = True  # keep the vendored world free of __pycache__

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_APWORLD = os.path.normpath(os.path.join(HERE, "..", "apworld", "star_fox_64_ss"))
OUT = os.path.normpath(os.path.join(HERE, "..", "src", "port", "archipelago", "ArchipelagoIds.h"))
OUT_TABLES = os.path.normpath(os.path.join(HERE, "..", "src", "port", "archipelago", "game", "ApTables.c"))
OUT_LOGIC_H = os.path.normpath(os.path.join(HERE, "..", "src", "port", "archipelago", "game", "ApLogic.h"))
OUT_LOGIC_C = os.path.normpath(os.path.join(HERE, "..", "src", "port", "archipelago", "game", "ApLogic.c"))


def load_world_data(world):
    """Import <world>/data as a package submodule without executing the world's __init__ (needs Archipelago)."""
    import types
    pkg = types.ModuleType("sf64_world_pkg")
    pkg.__path__ = [os.path.abspath(world)]
    sys.modules["sf64_world_pkg"] = pkg
    return importlib.import_module("sf64_world_pkg.data")


def world_dir(path):
    """Accept either the world package directory or an AP-Star-Fox-64 checkout (with an ap/ subdir)."""
    if os.path.isfile(os.path.join(path, "ids.py")):
        return path
    if os.path.isfile(os.path.join(path, "ap", "ids.py")):
        return os.path.join(path, "ap")
    raise SystemExit("no ids.py found under %s" % path)


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def name_to_c(s):
    s = re.sub("['\"]+", "", s)
    return re.sub("[^a-zA-Z0-9_]+", "_", s).upper()


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(apworld):
    apworld = world_dir(apworld)
    ids = load(os.path.join(apworld, "ids.py"), "sf64_ids")
    ver = load(os.path.join(apworld, "version.py"), "sf64_version")
    version = ver.version

    options = ids.option_name_to_id
    items = ids.item_name_to_id
    locations = ids.location_name_to_id
    group_items = ids.group_items
    group_locations = ids.group_locations

    item_max = max(items.values()) + 1
    loc_max = max(locations.values()) + 1
    opt_max = max(options.values()) + 1

    item_names = {v: k for k, v in items.items() if v >= 0}
    loc_names = {v: k for k, v in locations.items() if v >= 0}
    opt_names = {v: k for k, v in options.items()}

    item_groups = sorted(group_items.keys())
    loc_groups = sorted(group_locations.keys())
    item_group_of = {}
    for g, names in group_items.items():
        for n in names:
            item_group_of[items[n]] = g
    loc_group_of = {}
    for g, names in group_locations.items():
        for n in names:
            loc_group_of[locations[n]] = g
    # Checkpoint locations share their name with the checkpoint item.
    loc_checkpoint_item = {}
    for n in group_locations.get("Checkpoints", []):
        if n in items:
            loc_checkpoint_item[locations[n]] = items[n]

    o = []
    w = o.append
    w("#pragma once")
    w("")
    w("// Automatically generated by tools/ap_gen_ids.py from AP-Star-Fox-64 v%s. DO NOT EDIT." % version.as_string())
    w("// Regenerate with: python3 tools/ap_gen_ids.py (source: apworld/star_fox_64_ss)")
    w("")
    w("#include <stdint.h>")
    w("")
    w("#define AP_GAME_NAME \"Star Fox 64\"")
    w("#define AP_WORLD_VERSION_MAJOR %d" % version.major)
    w("#define AP_WORLD_VERSION_MINOR %d" % version.minor)
    w("#define AP_WORLD_VERSION_BUILD %d" % version.build)
    w("#define AP_WORLD_VERSION_U32 0x%08Xu" % version.as_u32())
    w("#define AP_WORLD_VERSION_STRING \"%s\"" % version.as_string())
    w("")

    w("typedef enum {")
    for k, v in options.items():
        w("    AP_OPTION_%s = %d," % (name_to_c(k), v))
    w("    AP_OPTION_MAX = %d," % opt_max)
    w("} ApOption;")
    w("")
    # Choice value enums, from the option classes in options.py.
    for key, choices in parse_options(apworld)["choices"].items():
        w("typedef enum {")
        for choice, value in choices.items():
            w("    AP_OPTION_%s_%s = %d," % (name_to_c(key), name_to_c(choice), value))
        w("} ApOption%s;" % "".join(part.capitalize() for part in key.split("_")))
        w("")

    w("typedef enum {")
    w("    AP_ITEM_NONE = -1,")
    for v in sorted(item_names):
        w("    AP_ITEM_%s = %d," % (name_to_c(item_names[v]), v))
    w("    AP_ITEM_MAX = %d," % item_max)
    w("} ApItem;")
    w("")
    w("typedef enum {")
    w("    AP_ITEM_TYPE_NONE = -1,")
    for i, g in enumerate(item_groups):
        w("    AP_ITEM_TYPE_%s = %d," % (name_to_c(g), i))
    w("} ApItemType;")
    w("")

    w("typedef enum {")
    w("    AP_LOCATION_NONE = -1,")
    for v in sorted(loc_names):
        w("    AP_LOCATION_%s = %d," % (name_to_c(loc_names[v]), v))
    w("    AP_LOCATION_MAX = %d," % loc_max)
    w("} ApLocation;")
    w("#define AP_LOCATION_MAX_BYTES ((AP_LOCATION_MAX + 7) / 8)")
    w("")
    w("typedef enum {")
    w("    AP_LOCATION_GROUP_NONE = -1,")
    for i, g in enumerate(loc_groups):
        w("    AP_LOCATION_GROUP_%s = %d," % (name_to_c(g), i))
    w("} ApLocationGroup;")
    w("")

    w("#ifdef AP_IDS_DEFINE_TABLES")
    w("#define AP_IDS_TABLE")
    w("#else")
    w("#define AP_IDS_TABLE extern")
    w("#endif")
    w("")
    w("#ifdef __cplusplus")
    w('extern "C" {')
    w("#endif")
    w("")

    def table(decl, entries, fmt):
        w("AP_IDS_TABLE %s" % decl)
        w("#ifdef AP_IDS_DEFINE_TABLES")
        w("= {")
        for e in entries:
            w("    " + fmt(e) + ",")
        w("}")
        w("#endif")
        w(";")
        w("")

    table("const char* const gApOptionNames[AP_OPTION_MAX]", range(opt_max),
          lambda i: cstr(opt_names.get(i, "")))
    table("const char* const gApItemNames[AP_ITEM_MAX]", range(item_max),
          lambda i: cstr(item_names.get(i, "")))
    table("const char* const gApLocationNames[AP_LOCATION_MAX]", range(loc_max),
          lambda i: cstr(loc_names.get(i, "")))
    table("const int8_t gApItemType[AP_ITEM_MAX]", range(item_max),
          lambda i: ("AP_ITEM_TYPE_" + name_to_c(item_group_of[i])) if i in item_group_of else "AP_ITEM_TYPE_NONE")
    table("const int8_t gApLocationGroup[AP_LOCATION_MAX]", range(loc_max),
          lambda i: ("AP_LOCATION_GROUP_" + name_to_c(loc_group_of[i])) if i in loc_group_of else "AP_LOCATION_GROUP_NONE")
    table("const int8_t gApLocationCheckpointItem[AP_LOCATION_MAX]", range(loc_max),
          lambda i: ("AP_ITEM_" + name_to_c(item_names[loc_checkpoint_item[i]])) if i in loc_checkpoint_item else "AP_ITEM_NONE")

    w("#ifdef __cplusplus")
    w("}")
    w("#endif")
    w("")
    return "\n".join(o)


def parse_options(apworld):
    """Read options.py with ast (it imports Archipelago, so it cannot be executed here).

    Returns {"classes": {ClassName: option_key}, "choices": {option_key: {choice_name: value}},
             "kinds": {option_key: "Choice"|"Toggle"|"Range"|...}}."""
    import ast
    world = world_dir(apworld)
    tree = ast.parse(open(os.path.join(world, "options.py"), encoding="utf-8").read())
    kinds = {}
    choices_by_class = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        bases = [b.id if isinstance(b, ast.Name) else getattr(b, "attr", "") for b in node.bases]
        kinds[node.name] = bases[0] if bases else ""
        vals = {}
        for stmt in node.body:
            if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1 and isinstance(stmt.targets[0], ast.Name):
                name = stmt.targets[0].id
                if name.startswith("option_") and isinstance(stmt.value, ast.Constant):
                    vals[name[len("option_"):]] = stmt.value.value
        if vals:
            choices_by_class[node.name] = vals
    classes = {}
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name.endswith("OptionsList"):
            for stmt in node.body:
                if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name) and isinstance(stmt.annotation, ast.Name):
                    classes[stmt.annotation.id] = stmt.target.id
    choices = {classes[c]: v for c, v in choices_by_class.items() if c in classes}
    return {"classes": classes, "choices": choices, "kinds": {classes[c]: k for c, k in kinds.items() if c in classes}}


class LogicCompiler:
    """Compiles the world's logic strings (see rules.py) into C boolean expressions.

    Items become count checks, options become AP_GetOption() reads, choice strings become the generated
    AP_OPTION_<OPTION>_<CHOICE> enumerators. Everything is evaluated at run time in the client, so no
    constant folding is done (the Python side folds because it knows the options at generation)."""

    def __init__(self, item_names, options):
        import re as _re
        self.items = {_re.sub("[^a-zA-Z0-9]+", "", n): n for n in item_names}
        self.classes = options["classes"]  # ClassName -> option key
        self.choices = options["choices"]

    def item_c(self, name):
        return "AP_ITEM_" + name_to_c(name)

    def option_c(self, key):
        return "AP_GetOption(AP_OPTION_%s)" % name_to_c(key)

    def compile(self, logic, where):
        import ast
        src = " ".join(logic.split())
        if src == "":
            return "false"
        tree = ast.parse(src, mode="eval")
        self.where = where
        return self.expr(tree.body)

    def fail(self, msg):
        raise SystemExit("%s: %s" % (self.where, msg))

    # An option reference used as a value (in comparisons / counts)
    def option_value(self, node):
        import ast
        if isinstance(node, ast.Name) and node.id in self.classes:
            return self.option_c(self.classes[node.id])
        return None

    def expr(self, node):
        import ast
        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool):
                return "true" if node.value else "false"
            self.fail("bare constant %r" % (node.value,))
        if isinstance(node, ast.Name):
            if node.id == "true":
                return "true"
            if node.id == "false":
                return "false"
            if node.id in self.items:
                return "(ApLogic_Count(%s) >= 1)" % self.item_c(self.items[node.id])
            if node.id in self.classes:
                return "(%s != 0)" % self.option_c(self.classes[node.id])
            self.fail("unknown name %s" % node.id)
        if isinstance(node, ast.Tuple):
            if len(node.elts) != 2 or not isinstance(node.elts[0], ast.Name) or node.elts[0].id not in self.items:
                self.fail("tuple must be (Item, count)")
            item = self.item_c(self.items[node.elts[0].id])
            count = node.elts[1]
            if isinstance(count, ast.Constant) and isinstance(count.value, int):
                if count.value <= 0:
                    return "true"
                return "(ApLogic_Count(%s) >= %d)" % (item, count.value)
            opt = self.option_value(count)
            if opt is None:
                self.fail("unsupported count expression")
            return "(ApLogic_Count(%s) >= %s)" % (item, opt)
        if isinstance(node, ast.BoolOp):
            op = " && " if isinstance(node.op, ast.And) else " || "
            return "(" + op.join(self.expr(v) for v in node.values) + ")"
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
            return "(!%s)" % self.expr(node.operand)
        if isinstance(node, ast.Compare):
            if len(node.ops) != 1 or len(node.comparators) != 1:
                self.fail("chained comparisons are not supported")
            left, op, right = node.left, node.ops[0], node.comparators[0]
            ops = {ast.Eq: "==", ast.NotEq: "!=", ast.Lt: "<", ast.LtE: "<=", ast.Gt: ">", ast.GtE: ">="}
            if type(op) not in ops:
                self.fail("unsupported comparison")
            key = None
            if isinstance(left, ast.Name) and left.id in self.classes:
                key = self.classes[left.id]
            lhs = self.value(left, key)
            rhs = self.value(right, key)
            return "(%s %s %s)" % (lhs, ops[type(op)], rhs)
        self.fail("unsupported expression %s" % type(node).__name__)

    def value(self, node, option_key):
        """A comparison operand: option, integer, boolean, or a choice name of option_key."""
        import ast
        opt = self.option_value(node)
        if opt is not None:
            return opt
        if isinstance(node, ast.Constant):
            if isinstance(node.value, bool):
                return "1" if node.value else "0"
            if isinstance(node.value, int):
                return str(node.value)
            if isinstance(node.value, str):
                if option_key is None or node.value not in self.choices.get(option_key, {}):
                    self.fail("unknown choice %r" % node.value)
                return "AP_OPTION_%s_%s" % (name_to_c(option_key), name_to_c(node.value))
        if isinstance(node, ast.Tuple):
            self.fail("count tuples cannot be compared")
        self.fail("unsupported comparison operand")


def generate_logic(world):
    """Emit ApLogic.h / ApLogic.c: region graph + compiled rules for the in-game tracker."""
    data = load_world_data(world)
    regions = data.regions
    ids = load(os.path.join(world, "ids.py"), "sf64_ids_logic")
    options = parse_options(world)
    compiler = LogicCompiler(ids.item_name_to_id.keys(), options)
    loc_enum = {name: "AP_LOCATION_" + name_to_c(name) for name in ids.location_name_to_id}
    region_names = list(regions.keys())
    region_enum = {rn: "AP_REGION_" + name_to_c(rn) for rn in region_names}

    rules = []  # (fn name, C expression, comment)

    def rule_fn(logic, where):
        expr = compiler.compile(logic, where)
        if expr == "true":
            return "NULL"
        name = "Rule%d" % len(rules)
        rules.append((name, expr, where))
        return name

    exits = []  # (from region, to region, rule fn)
    locations = {}  # location enum -> (region enum, rule fn)
    for rn, r in regions.items():
        for en, ex in r.get("exits", {}).items():
            if en not in regions:
                raise SystemExit("exit %s -> %s targets an unknown region" % (rn, en))
            exits.append((region_enum[rn], region_enum[en], rule_fn(ex.get("logic", "true"), "%s -> %s" % (rn, en))))
        for ln, loc in r.get("locations", {}).items():
            if rn == "Menu" or ln not in loc_enum:
                continue  # Menu entries are pre-collects (e.g. "Starting Level"), never real locations
            locations[loc_enum[ln]] = (region_enum[rn], rule_fn(loc.get("logic", "true"), "%s: %s" % (rn, ln)))

    h = []
    w = h.append
    w("#pragma once")
    w("")
    w("// Automatically generated by tools/ap_gen_ids.py from the apworld data. DO NOT EDIT.")
    w("// Region graph and access rules compiled from the world's logic strings, for the in-game tracker.")
    w("")
    w("#include <stdint.h>")
    w("#include <stdbool.h>")
    w('#include "port/archipelago/ArchipelagoIds.h"')
    w("")
    w("#ifdef __cplusplus")
    w('extern "C" {')
    w("#endif")
    w("")
    w("typedef enum {")
    for rn in region_names:
        w("    %s," % region_enum[rn])
    w("    AP_REGION_MAX,")
    w("} ApRegion;")
    w("")
    w("extern const char* const gApRegionNames[AP_REGION_MAX];")
    w("extern const int8_t gApRegionPlanet[AP_REGION_MAX]; // PlanetId, -1 for non-level regions")
    w("")
    w("void ApLogic_Update(void);                    // recompute region reachability from the current state")
    w("bool ApLogic_RegionReachable(int region);")
    w("int ApLogic_LocationRegion(uint16_t location); // -1 if the id is not a location")
    w("bool ApLogic_LocationRule(uint16_t location);  // the location's own rule, ignoring reachability")
    w("bool ApLogic_LocationInLogic(uint16_t location); // reachable region && rule")
    w("")
    w("#ifdef __cplusplus")
    w("}")
    w("#endif")
    w("")

    c = []
    w = c.append
    w("// Automatically generated by tools/ap_gen_ids.py from the apworld data. DO NOT EDIT.")
    w("// Source: apworld/%s/data (logic strings) and options.py" % os.path.basename(os.path.normpath(world)))
    w("")
    w('#include "ApGame.h"')
    w('#include "ApLogic.h"')
    w("")
    w("// Received count of an item as the logic sees it (medals may be earned locally when unshuffled).")
    w("static int ApLogic_Count(int item) {")
    w("    if (item == AP_ITEM_MEDAL) {")
    w("        return ApMission_MedalCount();")
    w("    }")
    w("    return AP_GetItemCount((uint16_t) item);")
    w("}")
    w("")
    w("typedef bool (*ApRuleFn)(void);")
    w("")
    for name, expr, where in rules:
        w("// %s" % where)
        w("static bool %s(void) {" % name)
        w("    return %s;" % expr)
        w("}")
        w("")
    w("const char* const gApRegionNames[AP_REGION_MAX] = {")
    for rn in region_names:
        w("    %s," % cstr(rn))
    w("};")
    w("")
    w("const int8_t gApRegionPlanet[AP_REGION_MAX] = {")
    for rn in region_names:
        planet = regions[rn].get("meta", {}).get("planet")
        w("    %s, // %s" % (planet if planet else "-1", rn))
    w("};")
    w("")
    w("typedef struct {")
    w("    uint8_t from;")
    w("    uint8_t to;")
    w("    ApRuleFn rule; // NULL = always")
    w("} ApExit;")
    w("")
    w("static const ApExit sExits[%d] = {" % len(exits))
    for frm, to, fn in exits:
        w("    { %s, %s, %s }," % (frm, to, fn))
    w("};")
    w("")
    w("typedef struct {")
    w("    int8_t region; // -1 = not a location")
    w("    ApRuleFn rule;")
    w("} ApLocationRule;")
    w("")
    w("static const ApLocationRule sLocations[AP_LOCATION_MAX] = {")
    id_to_name = {v: k for k, v in ids.location_name_to_id.items() if v >= 0}
    for lid in range(max(ids.location_name_to_id.values()) + 1):
        name = id_to_name.get(lid)
        entry = locations.get(loc_enum.get(name)) if name else None
        if entry:
            w("    { %s, %s }, // %s" % (entry[0], entry[1], name))
        else:
            w("    { -1, NULL }, // %s" % (name if name else "unused"))
    w("};")
    w("")
    w("static bool sReachable[AP_REGION_MAX];")
    w("")
    w("void ApLogic_Update(void) {")
    w("    bool changed = true;")
    w("    int i;")
    w("")
    w("    for (i = 0; i < AP_REGION_MAX; i++) {")
    w("        sReachable[i] = false;")
    w("    }")
    w("    sReachable[%s] = true;" % region_enum["Menu"])
    w("    while (changed) {")
    w("        changed = false;")
    w("        for (i = 0; i < ARRAY_COUNT(sExits); i++) {")
    w("            if (!sReachable[sExits[i].from] || sReachable[sExits[i].to]) {")
    w("                continue;")
    w("            }")
    w("            if ((sExits[i].rule == NULL) || sExits[i].rule()) {")
    w("                sReachable[sExits[i].to] = true;")
    w("                changed = true;")
    w("            }")
    w("        }")
    w("    }")
    w("}")
    w("")
    w("bool ApLogic_RegionReachable(int region) {")
    w("    return (region >= 0) && (region < AP_REGION_MAX) && sReachable[region];")
    w("}")
    w("")
    w("int ApLogic_LocationRegion(uint16_t location) {")
    w("    return (location < AP_LOCATION_MAX) ? sLocations[location].region : -1;")
    w("}")
    w("")
    w("bool ApLogic_LocationRule(uint16_t location) {")
    w("    if ((location >= AP_LOCATION_MAX) || (sLocations[location].region < 0)) {")
    w("        return false;")
    w("    }")
    w("    return (sLocations[location].rule == NULL) || sLocations[location].rule();")
    w("}")
    w("")
    w("bool ApLogic_LocationInLogic(uint16_t location) {")
    w("    return ApLogic_LocationRule(location) && ApLogic_RegionReachable(ApLogic_LocationRegion(location));")
    w("}")
    w("")
    return "\n".join(h), "\n".join(c)


# LevelId / PlanetId enum values from include/sf64level.h (needed to emit dense lookup tables).
LEVEL_IDS = {
    "LEVEL_CORNERIA": 0, "LEVEL_METEO": 1, "LEVEL_SECTOR_X": 2, "LEVEL_AREA_6": 3, "LEVEL_UNK_4": 4,
    "LEVEL_SECTOR_Y": 5, "LEVEL_VENOM_1": 6, "LEVEL_SOLAR": 7, "LEVEL_ZONESS": 8, "LEVEL_VENOM_ANDROSS": 9,
    "LEVEL_TRAINING": 10, "LEVEL_MACBETH": 11, "LEVEL_TITANIA": 12, "LEVEL_AQUAS": 13, "LEVEL_FORTUNA": 14,
    "LEVEL_UNK_15": 15, "LEVEL_KATINA": 16, "LEVEL_BOLSE": 17, "LEVEL_SECTOR_Z": 18, "LEVEL_VENOM_2": 19,
}
PLANET_IDS = {
    "PLANET_METEO": 0, "PLANET_AREA_6": 1, "PLANET_BOLSE": 2, "PLANET_SECTOR_Z": 3, "PLANET_SECTOR_X": 4,
    "PLANET_SECTOR_Y": 5, "PLANET_KATINA": 6, "PLANET_MACBETH": 7, "PLANET_ZONESS": 8, "PLANET_CORNERIA": 9,
    "PLANET_TITANIA": 10, "PLANET_AQUAS": 11, "PLANET_FORTUNA": 12, "PLANET_VENOM": 13, "PLANET_SOLAR": 14,
}
STATUS_INDEX = {"complete": 0, "accomplished": 1, "warp": 2}  # MissionStatus enum order


def generate_tables(world):
    data = load_world_data(world)
    regions = data.regions
    ids = load(os.path.join(world, "ids.py"), "sf64_ids_tables")
    loc_enum = {name: "AP_LOCATION_" + name_to_c(name) for name in ids.location_name_to_id}
    item_enum = {name: "AP_ITEM_" + name_to_c(name) for name in ids.item_name_to_id}
    opt_enum = {name: "AP_OPTION_" + name_to_c(name) for name in ids.option_name_to_id}
    levels = {rn: r for rn, r in regions.items() if "meta" in r}  # level regions only

    def meta(rn, key):
        return levels[rn]["meta"][key]

    def region_planet(rn):
        return meta(rn, "planet")

    # --- per-level static object indices (freestanding items + checkpoints)
    static = {}  # level enum -> [(index, location enum)]
    clear = {}   # (planet enum, status idx) -> location enum
    medal_by_planet = {}  # planet enum -> location enum
    medal_by_level = {}   # level enum -> location enum
    for rn, r in levels.items():
        level = meta(rn, "level")
        planet = meta(rn, "planet")
        for ln, loc in r.get("locations", {}).items():
            if "object_index" in loc:
                static.setdefault(level, []).append((loc["object_index"], loc_enum[ln]))
            if "status" in loc:
                key = (planet, STATUS_INDEX[loc["status"]])
                if key in clear:
                    raise SystemExit("duplicate clear location for %s/%s" % key)
                clear[key] = loc_enum[ln]
            if loc.get("group") == "Medals":
                medal_by_planet[planet] = loc_enum[ln]
                medal_by_level[level] = loc_enum[ln]
        if planet in medal_by_planet and level not in medal_by_level:
            medal_by_level[level] = medal_by_planet[planet]
    # levels sharing a planet (Venom 1 / Venom 2 / Venom) share the planet's medal location
    for rn, r in levels.items():
        medal_by_level.setdefault(meta(rn, "level"), medal_by_planet.get(meta(rn, "planet"), "AP_LOCATION_NONE"))

    # --- paths: level exit -> (from planet, to planet, path item)
    paths = []
    for rn, r in levels.items():
        for en, ex in r.get("exits", {}).items():
            if "path" not in ex:
                continue
            if en not in levels:
                raise SystemExit("exit %s -> %s targets a non-level region" % (rn, en))
            paths.append((region_planet(rn), region_planet(en), item_enum[ex["path"]]))

    # --- planet -> level (a planet with several levels declares which one the map uses via the region
    #     whose level_item is the planet's own name; Venom uses the Andross level as in Map_GetPlanetId)
    planet_level = {}
    for rn, r in levels.items():
        planet, level = meta(rn, "planet"), meta(rn, "level")
        planet_level.setdefault(planet, level)
        if rn == meta(rn, "level_item"):  # the region named after the level item is the canonical one
            planet_level[planet] = level

    o = []
    w = o.append
    w("// Automatically generated by tools/ap_gen_ids.py from the apworld data. DO NOT EDIT.")
    w("// Source: apworld/%s/data" % os.path.basename(os.path.normpath(world)))
    w("")
    w('#include "ApGame.h"')
    w("")
    w("s16 ApTables_GetStaticLocation(LevelId level, s32 index) {")
    w("    switch (level) {")
    for level in sorted(static, key=lambda l: LEVEL_IDS[l]):
        w("        case %s:" % level)
        w("            switch (index) {")
        for idx, loc in sorted(static[level]):
            w("                case 0x%04X:" % idx)
            w("                    return %s;" % loc)
        w("            }")
        w("            break;")
    w("        default:")
    w("            break;")
    w("    }")
    w("    return AP_LOCATION_NONE;")
    w("}")
    w("")
    w("// [PlanetId][MissionStatus]")
    w("static const s16 sClearLocations[PLANET_MAX][3] = {")
    for planet in sorted(PLANET_IDS, key=PLANET_IDS.get):
        row = [clear.get((planet, s), "AP_LOCATION_NONE") for s in range(3)]
        w("    /* %-16s */ { %s }," % (planet, ", ".join(row)))
    w("};")
    w("")
    w("s16 ApTables_ClearLocation(PlanetId planet, s32 missionStatus) {")
    w("    if ((planet < 0) || (planet >= PLANET_MAX) || (missionStatus < 0) || (missionStatus > 2)) {")
    w("        return AP_LOCATION_NONE;")
    w("    }")
    w("    return sClearLocations[planet][missionStatus];")
    w("}")
    w("")
    w("static const s16 sMedalLocationsByPlanet[PLANET_MAX] = {")
    for planet in sorted(PLANET_IDS, key=PLANET_IDS.get):
        w("    /* %-16s */ %s," % (planet, medal_by_planet.get(planet, "AP_LOCATION_NONE")))
    w("};")
    w("")
    w("s16 ApTables_MedalLocationForPlanet(PlanetId planet) {")
    w("    if ((planet < 0) || (planet >= PLANET_MAX)) {")
    w("        return AP_LOCATION_NONE;")
    w("    }")
    w("    return sMedalLocationsByPlanet[planet];")
    w("}")
    w("")

    def level_switch(name, ret_type, mapping, default):
        w("%s %s(LevelId level) {" % (ret_type, name))
        w("    switch (level) {")
        by_value = {}
        for level, value in mapping.items():
            by_value.setdefault(value, []).append(level)
        for value, lvls in sorted(by_value.items(), key=lambda kv: min(LEVEL_IDS[l] for l in kv[1])):
            for l in sorted(lvls, key=LEVEL_IDS.get):
                w("        case %s:" % l)
            w("            return %s;" % value)
        w("        default:")
        w("            return %s;" % default)
        w("    }")
        w("}")
        w("")

    level_switch("ApTables_MedalLocationForLevel", "s16", medal_by_level, "AP_LOCATION_NONE")
    level_switch("ApTables_MedalOption", "s16",
                 {meta(rn, "level"): opt_enum[meta(rn, "medal_option")] for rn in levels}, "-1")
    level_switch("ApTables_LevelItem", "s16",
                 {meta(rn, "level"): item_enum[meta(rn, "level_item")] for rn in levels}, "AP_ITEM_NONE")

    w("static const LevelId sPlanetToLevel[PLANET_MAX] = {")
    for planet in sorted(PLANET_IDS, key=PLANET_IDS.get):
        w("    /* %-16s */ %s," % (planet, planet_level[planet]))
    w("};")
    w("")
    w("LevelId ApTables_PlanetToLevel(PlanetId planet) {")
    w("    if ((planet < 0) || (planet >= PLANET_MAX)) {")
    w("        return LEVEL_UNK_M1;")
    w("    }")
    w("    return sPlanetToLevel[planet];")
    w("}")
    w("")
    w("typedef struct {")
    w("    PlanetId from;")
    w("    PlanetId to;")
    w("    s16 item;")
    w("} ApPathEntry;")
    w("")
    w("static const ApPathEntry sPaths[%d] = {" % len(paths))
    for frm, to, item in sorted(paths, key=lambda p: (PLANET_IDS[p[0]], PLANET_IDS[p[1]])):
        w("    { %s, %s, %s }," % (frm, to, item))
    w("};")
    w("")
    w("s16 ApTables_PathItem(PlanetId from, PlanetId to) {")
    w("    s32 i;")
    w("")
    w("    for (i = 0; i < ARRAY_COUNT(sPaths); i++) {")
    w("        if ((sPaths[i].from == from) && (sPaths[i].to == to)) {")
    w("            return sPaths[i].item;")
    w("        }")
    w("    }")
    w("    return AP_ITEM_NONE;")
    w("}")
    w("")
    w("bool ApTables_IsCheckpointLocation(s16 loc) {")
    w("    return (loc > 0) && (loc < AP_LOCATION_MAX) && (gApLocationGroup[loc] == AP_LOCATION_GROUP_CHECKPOINTS);")
    w("}")
    w("")
    w("s16 ApTables_CheckpointItem(s16 loc) {")
    w("    if ((loc <= 0) || (loc >= AP_LOCATION_MAX)) {")
    w("        return AP_ITEM_NONE;")
    w("    }")
    w("    return gApLocationCheckpointItem[loc];")
    w("}")
    w("")
    return "\n".join(o)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apworld", default=DEFAULT_APWORLD)
    ap.add_argument("--check", action="store_true", help="exit 1 if the header is out of date")
    args = ap.parse_args()
    world = world_dir(args.apworld)
    logic_h, logic_c = generate_logic(world)
    outputs = [(OUT, generate(args.apworld)), (OUT_TABLES, generate_tables(world)), (OUT_LOGIC_H, logic_h),
               (OUT_LOGIC_C, logic_c)]
    if args.check:
        stale = False
        for path, text in outputs:
            try:
                with open(path, "r", encoding="utf-8") as f:
                    current = f.read()
            except FileNotFoundError:
                current = None
            if current != text:
                print("%s is out of date" % path, file=sys.stderr)
                stale = True
            else:
                print("%s is up to date" % path)
        return 1 if stale else 0
    for path, text in outputs:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print("wrote %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
