#!/usr/bin/env python3
"""Generate src/port/archipelago/ArchipelagoIds.h from the AP-Star-Fox-64 apworld.

Usage: tools/ap_gen_ids.py [--apworld PATH] [--check]

Reads ap/ids.py and ap/version.py from the apworld checkout (plain dicts, no
Archipelago install needed) and emits C enums + name tables. Enum names use the
same name_to_c() rule as the ROM hack's tools/enum_gen.py so that game code can
be ported verbatim from n64/src/.
"""
import argparse
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_APWORLD = os.path.normpath(os.path.join(HERE, "..", "..", "AP-Star-Fox-64"))
OUT = os.path.normpath(os.path.join(HERE, "..", "src", "port", "archipelago", "ArchipelagoIds.h"))


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def name_to_c(s):
    s = re.sub("['\"]+", "", s)
    return re.sub("[^a-zA-Z0-9_]+", "_", s).upper()


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(apworld):
    ids = load(os.path.join(apworld, "ap", "ids.py"), "sf64_ids")
    ver = load(os.path.join(apworld, "ap", "version.py"), "sf64_version")
    version = ver.version

    options = ids.option_name_to_id
    items = ids.item_name_to_id
    locations = ids.location_name_to_id
    group_items = ids.group_items
    group_locations = ids.group_locations

    item_max = max(items.values()) + 1
    loc_max = max(locations.values()) + 1
    opt_max = max(options.values()) + 1

    item_names = {v: k for k, v in items.items() if v >= 0}
    loc_names = {v: k for k, v in locations.items() if v >= 0}
    opt_names = {v: k for k, v in options.items()}

    item_groups = sorted(group_items.keys())
    loc_groups = sorted(group_locations.keys())
    item_group_of = {}
    for g, names in group_items.items():
        for n in names:
            item_group_of[items[n]] = g
    loc_group_of = {}
    for g, names in group_locations.items():
        for n in names:
            loc_group_of[locations[n]] = g
    # Checkpoint locations share their name with the checkpoint item.
    loc_checkpoint_item = {}
    for n in group_locations.get("Checkpoints", []):
        if n in items:
            loc_checkpoint_item[locations[n]] = items[n]

    o = []
    w = o.append
    w("#pragma once")
    w("")
    w("// Automatically generated by tools/ap_gen_ids.py from AP-Star-Fox-64 v%s. DO NOT EDIT." % version.as_string())
    w("// Regenerate with: python3 tools/ap_gen_ids.py [--apworld ../AP-Star-Fox-64]")
    w("")
    w("#include <stdint.h>")
    w("")
    w("#define AP_GAME_NAME \"Star Fox 64\"")
    w("#define AP_WORLD_VERSION_MAJOR %d" % version.major)
    w("#define AP_WORLD_VERSION_MINOR %d" % version.minor)
    w("#define AP_WORLD_VERSION_BUILD %d" % version.build)
    w("#define AP_WORLD_VERSION_U32 0x%08Xu" % version.as_u32())
    w("#define AP_WORLD_VERSION_STRING \"%s\"" % version.as_string())
    w("")

    w("typedef enum {")
    for k, v in options.items():
        w("    AP_OPTION_%s = %d," % (name_to_c(k), v))
    w("    AP_OPTION_MAX = %d," % opt_max)
    w("} ApOption;")
    w("")
    # Option choice enums (mirrors n64/src/ap/options.h); hard-coded because
    # ids.py does not carry choice names.
    w("typedef enum {")
    w("    AP_OPTION_VICTORY_CONDITION_ANDROSS_OR_ROBOT_ANDROSS = 0,")
    w("    AP_OPTION_VICTORY_CONDITION_ANDROSS_AND_ROBOT_ANDROSS = 1,")
    w("    AP_OPTION_VICTORY_CONDITION_ANDROSS = 2,")
    w("} ApOptionVictoryCondition;")
    w("")
    w("typedef enum {")
    w("    AP_OPTION_LEVEL_ACCESS_SHUFFLE_LEVELS = 0,")
    w("    AP_OPTION_LEVEL_ACCESS_SHUFFLE_PATHS = 1,")
    w("} ApOptionLevelAccess;")
    w("")

    w("typedef enum {")
    w("    AP_ITEM_NONE = -1,")
    for v in sorted(item_names):
        w("    AP_ITEM_%s = %d," % (name_to_c(item_names[v]), v))
    w("    AP_ITEM_MAX = %d," % item_max)
    w("} ApItem;")
    w("")
    w("typedef enum {")
    w("    AP_ITEM_TYPE_NONE = -1,")
    for i, g in enumerate(item_groups):
        w("    AP_ITEM_TYPE_%s = %d," % (name_to_c(g), i))
    w("} ApItemType;")
    w("")

    w("typedef enum {")
    w("    AP_LOCATION_NONE = -1,")
    for v in sorted(loc_names):
        w("    AP_LOCATION_%s = %d," % (name_to_c(loc_names[v]), v))
    w("    AP_LOCATION_MAX = %d," % loc_max)
    w("} ApLocation;")
    w("#define AP_LOCATION_MAX_BYTES ((AP_LOCATION_MAX + 7) / 8)")
    w("")
    w("typedef enum {")
    w("    AP_LOCATION_GROUP_NONE = -1,")
    for i, g in enumerate(loc_groups):
        w("    AP_LOCATION_GROUP_%s = %d," % (name_to_c(g), i))
    w("} ApLocationGroup;")
    w("")

    w("#ifdef AP_IDS_DEFINE_TABLES")
    w("#define AP_IDS_TABLE")
    w("#else")
    w("#define AP_IDS_TABLE extern")
    w("#endif")
    w("")
    w("#ifdef __cplusplus")
    w('extern "C" {')
    w("#endif")
    w("")

    def table(decl, entries, fmt):
        w("AP_IDS_TABLE %s" % decl)
        w("#ifdef AP_IDS_DEFINE_TABLES")
        w("= {")
        for e in entries:
            w("    " + fmt(e) + ",")
        w("}")
        w("#endif")
        w(";")
        w("")

    table("const char* const gApOptionNames[AP_OPTION_MAX]", range(opt_max),
          lambda i: cstr(opt_names.get(i, "")))
    table("const char* const gApItemNames[AP_ITEM_MAX]", range(item_max),
          lambda i: cstr(item_names.get(i, "")))
    table("const char* const gApLocationNames[AP_LOCATION_MAX]", range(loc_max),
          lambda i: cstr(loc_names.get(i, "")))
    table("const int8_t gApItemType[AP_ITEM_MAX]", range(item_max),
          lambda i: ("AP_ITEM_TYPE_" + name_to_c(item_group_of[i])) if i in item_group_of else "AP_ITEM_TYPE_NONE")
    table("const int8_t gApLocationGroup[AP_LOCATION_MAX]", range(loc_max),
          lambda i: ("AP_LOCATION_GROUP_" + name_to_c(loc_group_of[i])) if i in loc_group_of else "AP_LOCATION_GROUP_NONE")
    table("const int8_t gApLocationCheckpointItem[AP_LOCATION_MAX]", range(loc_max),
          lambda i: ("AP_ITEM_" + name_to_c(item_names[loc_checkpoint_item[i]])) if i in loc_checkpoint_item else "AP_ITEM_NONE")

    w("#ifdef __cplusplus")
    w("}")
    w("#endif")
    w("")
    return "\n".join(o)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apworld", default=DEFAULT_APWORLD)
    ap.add_argument("--check", action="store_true", help="exit 1 if the header is out of date")
    args = ap.parse_args()
    text = generate(args.apworld)
    if args.check:
        try:
            with open(OUT, "r", encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            current = None
        if current != text:
            print("%s is out of date" % OUT, file=sys.stderr)
            return 1
        print("%s is up to date" % OUT)
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
